import 'package:hooks_riverpod/hooks_riverpod.dart';

import '../../../core/providers/database_provider.dart';
import '../../live_orders/state/cartivo_products_sync_provider.dart';
import '../../settings/state/store_info_notifier.dart';
import '../entities/discount.dart';
import '../entities/line_item.dart';
import '../entities/receipt.dart';
import '../entities/sale.dart';
import '../entities/sale_payment.dart';
import '../use_cases/finalize_sale.dart';

const _uncategorized = 'Uncategorized';

class OrderGroup {
  final String id;
  final String name;
  const OrderGroup({required this.id, required this.name});
}

class OrderVariant {
  final int id;
  final String name;
  final double price;
  final bool isAvailable;

  const OrderVariant({
    required this.id,
    required this.name,
    required this.price,
    required this.isAvailable,
  });
}

class OrderProduct {
  final int id;
  final String groupId;
  final String name;
  final double price;
  final bool isAvailable;
  final String? imageUrl;
  final List<OrderVariant> variants;

  const OrderProduct({
    required this.id,
    required this.groupId,
    required this.name,
    required this.price,
    required this.isAvailable,
    required this.variants,
    this.imageUrl,
  });
}

class OrderingData {
  final List<OrderGroup> groups;
  final List<OrderProduct> allProducts;
  final String? selectedGroupId;
  final Sale sale;

  const OrderingData({
    required this.groups,
    required this.allProducts,
    this.selectedGroupId,
    required this.sale,
  });

  List<OrderProduct> get filteredProducts {
    var list = allProducts.where((p) => p.isAvailable).toList();
    if (selectedGroupId != null) {
      list = list.where((p) => p.groupId == selectedGroupId).toList();
    }
    return list;
  }

  OrderingData copyWith({
    List<OrderGroup>? groups,
    List<OrderProduct>? allProducts,
    String? Function()? selectedGroupId,
    Sale? sale,
  }) =>
      OrderingData(
        groups: groups ?? this.groups,
        allProducts: allProducts ?? this.allProducts,
        selectedGroupId: selectedGroupId != null ? selectedGroupId() : this.selectedGroupId,
        sale: sale ?? this.sale,
      );
}

class OrderingNotifier extends AsyncNotifier<OrderingData> {
  @override
  Future<OrderingData> build() => _load();

  Future<OrderingData> _load() async {
    final db = ref.watch(databaseProvider);
    // Reload when a Cartivo sync lands new data.
    ref.watch(
      cartivoSyncStateProvider.select(
        (s) => (s.value?.watermark, s.value?.lastFullSyncAt),
      ),
    );
    final merchantId =
        (await ref.watch(storeInfoProvider.future))?.storeId ?? '';
    final dao = db.cartivoProductsDao;
    final productRows = await dao.getProducts(merchantId);
    final variantRows = await dao.getVariantsForMerchant(merchantId);

    final variantsByProduct = <int, List<OrderVariant>>{};
    for (final v in variantRows) {
      variantsByProduct.putIfAbsent(v.productId, () => []).add(
            OrderVariant(
              id: v.variantId,
              name: v.variantName,
              price: v.price,
              isAvailable: v.isAvailable && v.availableQuantity > 0,
            ),
          );
    }

    final products = <OrderProduct>[];
    for (final p in productRows) {
      final variants = variantsByProduct[p.productId] ?? const [];
      if (variants.isEmpty) continue;
      final sellable = variants.where((v) => v.isAvailable);
      final category = p.category?.trim() ?? '';
      products.add(OrderProduct(
        id: p.productId,
        groupId: category.isEmpty ? _uncategorized : category,
        name: p.name,
        price: (sellable.isEmpty ? variants : sellable)
            .map((v) => v.price)
            .reduce((a, b) => a < b ? a : b),
        isAvailable: sellable.isNotEmpty,
        imageUrl: p.imageUrl,
        variants: variants,
      ));
    }

    final groupNames = {for (final p in products) p.groupId}.toList()..sort();
    final groups = [for (final n in groupNames) OrderGroup(id: n, name: n)];

    final current = state.value;
    return OrderingData(
      groups: groups,
      allProducts: products,
      selectedGroupId: current?.selectedGroupId,
      sale: current?.sale ?? Sale.autoGenerated(),
    );
  }

  void selectGroup(String? groupId) {
    state = state.whenData((s) => s.copyWith(selectedGroupId: () => groupId));
  }

  void addItem(LineItem item) {
    state = state.whenData((s) {
      final items = s.sale.items;
      final existingIndex = items.indexWhere(
        (i) => i.discount == null && _isSameItem(i, item),
      );

      final List<LineItem> updatedItems;
      if (existingIndex != -1) {
        final existing = items[existingIndex];
        updatedItems = [...items];
        updatedItems[existingIndex] =
            existing.copyWith(quantity: existing.quantity + item.quantity);
      } else {
        updatedItems = [...items, item];
      }

      return s.copyWith(sale: s.sale.copyWith(items: updatedItems));
    });
  }

  static bool _isSameItem(LineItem a, LineItem b) {
    if (a.productId != b.productId) return false;
    if (a.variantName != b.variantName) return false;
    if (a.modifiers.length != b.modifiers.length) return false;

    final aGroups = [...a.modifiers]..sort((x, y) => x.groupId.compareTo(y.groupId));
    final bGroups = [...b.modifiers]..sort((x, y) => x.groupId.compareTo(y.groupId));

    for (var i = 0; i < aGroups.length; i++) {
      if (aGroups[i].groupId != bGroups[i].groupId) return false;
      final aOpts = [...aGroups[i].selected]..sort((x, y) => x.optionId.compareTo(y.optionId));
      final bOpts = [...bGroups[i].selected]..sort((x, y) => x.optionId.compareTo(y.optionId));
      if (aOpts.length != bOpts.length) return false;
      for (var j = 0; j < aOpts.length; j++) {
        if (aOpts[j].optionId != bOpts[j].optionId) return false;
      }
    }
    return true;
  }

  void removeItem(String lineItemId) {
    state = state.whenData((s) => s.copyWith(
          sale: s.sale.copyWith(
            items: s.sale.items.where((i) => i.id != lineItemId).toList(),
          ),
        ));
  }

  void updateQuantity(String lineItemId, int qty) {
    if (qty <= 0) {
      removeItem(lineItemId);
      return;
    }
    state = state.whenData((s) => s.copyWith(
          sale: s.sale.copyWith(
            items: s.sale.items
                .map((i) => i.id == lineItemId ? i.copyWith(quantity: qty) : i)
                .toList(),
          ),
        ));
  }

  void updateNotes(String lineItemId, String? notes) {
    state = state.whenData((s) => s.copyWith(
          sale: s.sale.copyWith(
            items: s.sale.items
                .map((i) => i.id == lineItemId
                    ? i.copyWith(notes: (notes?.isEmpty == true) ? null : notes)
                    : i)
                .toList(),
          ),
        ));
  }

  void applyDiscount(
    Map<String, int> selectedQuantities,
    Discount? Function(LineItem lineItem, int quantity) buildDiscount,
  ) {
    if (!state.hasValue || selectedQuantities.isEmpty) return;

    final currentLineItems = state.requireValue.sale.items;
    final newLineItems = <LineItem>[];

    for (final originalItem in currentLineItems) {
      final selectedQty = selectedQuantities[originalItem.id];

      if (selectedQty == null) {
        newLineItems.add(originalItem);
        continue;
      }

      if (selectedQty >= originalItem.quantity) {
        final discount = buildDiscount(originalItem, selectedQty);
        newLineItems.add(originalItem.copyWith(discount: () => discount));
      } else {
        final remainingQty = originalItem.quantity - selectedQty;
        newLineItems.add(originalItem.copyWith(quantity: remainingQty, discount: () => null));

        final discountedItem = originalItem.copyWith(
          id: '${originalItem.id}_split_${DateTime.now().microsecondsSinceEpoch}',
          quantity: selectedQty,
        );
        final discount = buildDiscount(discountedItem, selectedQty);
        newLineItems.add(discountedItem.copyWith(discount: () => discount));
      }
    }

    state = state.whenData((s) => s.copyWith(sale: s.sale.copyWith(items: newLineItems)));
  }

  /// Strips the discount off [lineItemId]. If an identical undiscounted line
  /// already exists (e.g. the remainder of a partial-quantity discount), the
  /// quantities are merged back into it.
  void removeDiscount(String lineItemId) {
    state = state.whenData((s) {
      final items = s.sale.items;
      final target = items.where((i) => i.id == lineItemId).firstOrNull;
      if (target == null || target.discount == null) return s;

      final mergeIndex = items.indexWhere(
        (i) => i.id != lineItemId && i.discount == null && _isSameItem(i, target),
      );

      final List<LineItem> updatedItems;
      if (mergeIndex != -1) {
        final existing = items[mergeIndex];
        updatedItems = [
          for (final i in items)
            if (i.id == existing.id)
              existing.copyWith(quantity: existing.quantity + target.quantity)
            else if (i.id != lineItemId)
              i,
        ];
      } else {
        updatedItems = [
          for (final i in items)
            i.id == lineItemId ? i.copyWith(discount: () => null) : i,
        ];
      }

      return s.copyWith(sale: s.sale.copyWith(items: updatedItems));
    });
  }

  void setSaleType(String type) {
    state = state.whenData((s) => s.copyWith(sale: s.sale.copyWith(type: type)));
  }

  void clearCart() {
    state = state.whenData(
      (s) => s.copyWith(sale: Sale.autoGenerated(type: s.sale.type)),
    );
  }

  Future<Receipt> confirmSale({
    required int cashierId,
    required String method,
    required double amountPaid,
    String? reference,
  }) async {
    final data = state.value!;
    final total = data.sale.total;
    final cashReceived = method == 'cash' ? amountPaid : total;

    final saleWithPayment = data.sale.copyWith(
      payment: () => SalePayment(
        method: method,
        amountPaid: method == 'cash' ? total : amountPaid,
        cashReceived: cashReceived,
        reference: reference,
      ),
    );

    final finalizeSale = ref.read(finalizeSaleProvider);
    final receipt = await finalizeSale(saleWithPayment, cashierId: cashierId);

    return receipt;
  }

  Future<void> refresh() async {
    state = const AsyncValue.loading();
    state = await AsyncValue.guard(_load);
  }
}

final orderingProvider =
    AsyncNotifierProvider<OrderingNotifier, OrderingData>(OrderingNotifier.new);
