import 'line_item.dart';
import 'sale_payment.dart';

class Sale {
  final int? id;
  final String type;
  final List<LineItem> items;
  final DateTime createdAt;
  final SalePayment? payment;
  final String soNumber;

  const Sale({
    this.id,
    required this.type,
    required this.items,
    required this.createdAt,
    this.payment,
    this.soNumber = '',
  });

  factory Sale.autoGenerated({String type = 'dine_in'}) =>
      Sale(type: type, items: const [], createdAt: DateTime.now());

  double get subtotal => items.fold(0.0, (s, i) => s + i.lineSubtotal);
  double get totalDiscount => items.fold(0.0, (s, i) => s + i.discountAmount);
  double get total => subtotal - totalDiscount;
  int get totalQuantity => items.fold(0, (s, i) => s + i.quantity);

  double get vatableAmount =>
      items.where((i) => !i.isVatExempt).fold(0.0, (s, i) => s + i.vatExclusiveAmount);
  double get vatAmount => items.fold(0.0, (s, i) => s + i.vatAmount);
  double get vatExemptSales =>
      items.where((i) => i.isVatExempt).fold(0.0, (s, i) => s + i.vatExclusiveAmount);

  Sale copyWith({
    int? id,
    String? type,
    List<LineItem>? items,
    SalePayment? Function()? payment,
    String? soNumber,
  }) =>
      Sale(
        id: id ?? this.id,
        type: type ?? this.type,
        items: items ?? this.items,
        createdAt: createdAt,
        payment: payment != null ? payment() : this.payment,
        soNumber: soNumber ?? this.soNumber,
      );
}
