import 'dart:async';

import 'package:dart_mappable/dart_mappable.dart';
import 'package:fast_immutable_collections/fast_immutable_collections.dart';
import 'package:hooks_riverpod/hooks_riverpod.dart';

import '../../../utils/uuidv7.dart';
import '../entities/cashier.dart';
import '../entities/discount.dart';
import '../entities/line_item.dart';
import '../entities/payment.dart';
import '../entities/product.dart';
import '../entities/product_group.dart';
import '../entities/receipt.dart';
import '../entities/sale.dart';
import '../entities/store.dart';
import '../enums/sale_type.dart';
import '../repositories/cashier_repository.dart';
import '../repositories/product_group_repository.dart';
import '../repositories/product_repository.dart';
import '../repositories/store_repository.dart';
import '../use_cases/finalize_sale.dart';

part 'ordering_notifier.mapper.dart';

@MappableClass()
class OrderingData with OrderingDataMappable {
  const OrderingData({
    required this.store,
    required this.cashier,
    required this.sale,
    required this.productGroups,
    required this.products,
    this.selectedGroup,
    this.receipt,
  });

  final Store store;
  final Cashier cashier;
  final Sale sale;
  final IList<ProductGroup> productGroups;
  final IList<Product> products;
  final ProductGroup? selectedGroup;
  final Receipt? receipt;
}

final orderingProvider = AsyncNotifierProvider(OrderingNotifier.new, name: 'orderingProvider');

class OrderingNotifier extends AsyncNotifier<OrderingData> {
  @override
  Future<OrderingData> build() async {
    final storeRepository = ref.watch(storeRepositoryProvider);
    final cashierRepository = ref.watch(cashierRepositoryProvider);
    final productGroupRepository = ref.watch(productGroupRepositoryProvider);
    final productRepository = ref.watch(productRepositoryProvider);

    final (store, cashier, productGroups) =
        await (
          storeRepository.getCurrent(),
          cashierRepository.getCurrent(),
          productGroupRepository.getAll(),
        ).wait;

    if (productGroups.isEmpty) {
      return OrderingData(
        store: store,
        cashier: cashier,
        sale: Sale.autoGenerated(type: SaleType.dineIn),
        productGroups: productGroups,
        products: const IList.empty(),
      );
    }

    final products = await productRepository.getByGroup(productGroups.first);

    return OrderingData(
      store: store,
      cashier: cashier,
      sale: Sale.autoGenerated(type: SaleType.dineIn),
      productGroups: productGroups,
      selectedGroup: productGroups.first,
      products: products,
    );
  }

  void applyDiscount(
    Map<String, int> selectedQuantities,
    Discount? Function(LineItem lineItem, int quantity) buildDiscount,
  ) {
    if (!state.hasValue || selectedQuantities.isEmpty) return;

    final sale = state.requireValue.sale;
    final currentLineItems = sale.items;
    final newLineItems = <LineItem>[];

    for (final originalItem in currentLineItems) {
      final selectedQty = selectedQuantities[originalItem.id];

      if (selectedQty == null) {
        newLineItems.add(originalItem);
      } else {
        if (selectedQty >= originalItem.quantity) {
          final discount = buildDiscount(originalItem, selectedQty);
          newLineItems.add(originalItem.copyWith(discount: discount));
        } else {
          final remainingQty = originalItem.quantity - selectedQty;
          newLineItems.add(originalItem.copyWith(quantity: remainingQty, discount: null));

          final discountedItem = originalItem.copyWith(
            id: UuidV7.generate(),
            quantity: selectedQty,
          );
          final discount = buildDiscount(discountedItem, selectedQty);
          newLineItems.add(discountedItem.copyWith(discount: discount));
        }
      }
    }

    state = AsyncData(
      state.requireValue.copyWith(sale: sale.copyWith(items: newLineItems.toIList())),
    );
  }

  void selectSaleType(SaleType saleType) {
    if (!state.hasValue) return;
    final sale = state.requireValue.sale;
    state = AsyncData(state.requireValue.copyWith(sale: sale.copyWith(type: saleType)));
  }

  Future<void> selectGroup(ProductGroup group) async {
    if (!state.hasValue) return;

    state = AsyncData(state.requireValue.copyWith(selectedGroup: group));

    state = const AsyncLoading();

    state = await AsyncValue.guard(() async {
      final products = await ref.read(productRepositoryProvider).getByGroup(group);
      return state.requireValue.copyWith(products: products);
    });
  }

  /// Re-fetches products for the currently selected group in the background.
  ///
  /// Unlike [selectGroup], this doesn't touch loading state or the in-progress
  /// sale — it's meant to be called silently (e.g. whenever the ordering
  /// screen becomes visible again) so products added/edited/deleted elsewhere
  /// (Catalog Management) show up without discarding the current cart.
  Future<void> refreshProducts() async {
    final current = state.value;
    final group = current?.selectedGroup;
    if (group == null) return;

    final products = await ref.read(productRepositoryProvider).getByGroup(group);

    if (!state.hasValue) return;
    state = AsyncData(state.requireValue.copyWith(products: products));
  }

  void addLineItem(LineItem lineItem) {
    if (!state.hasValue) return;

    final sale = state.requireValue.sale;
    final items = sale.items;

    final existingIndex = items.indexWhere(
      (it) => it.discount == null && _isSameItem(it, lineItem),
    );

    final IList<LineItem> updatedItems;
    if (existingIndex != -1) {
      final existing = items[existingIndex];
      updatedItems = items.replace(
        existingIndex,
        existing.copyWith(quantity: existing.quantity + lineItem.quantity),
      );
    } else {
      updatedItems = items.add(lineItem);
    }

    state = AsyncData(state.requireValue.copyWith(sale: sale.copyWith(items: updatedItems)));
  }

  static bool _isSameItem(LineItem a, LineItem b) {
    if (a.productId != b.productId) return false;
    if (a.variant.id != b.variant.id) return false;
    if (a.modifiers.length != b.modifiers.length) return false;

    final aMods = a.modifiers.toList()..sort((x, y) => x.id.compareTo(y.id));
    final bMods = b.modifiers.toList()..sort((x, y) => x.id.compareTo(y.id));

    for (var i = 0; i < aMods.length; i++) {
      if (aMods[i].id != bMods[i].id) return false;
      final aOpts = aMods[i].options.toList()..sort((x, y) => x.id.compareTo(y.id));
      final bOpts = bMods[i].options.toList()..sort((x, y) => x.id.compareTo(y.id));
      if (aOpts.length != bOpts.length) return false;
      for (var j = 0; j < aOpts.length; j++) {
        if (aOpts[j].id != bOpts[j].id) return false;
      }
    }
    return true;
  }

  void replaceLineItem(LineItem lineItem, {required int index}) {
    if (!state.hasValue) return;

    final sale = state.requireValue.sale;
    var lineItems = sale.items;

    if (lineItem.quantity > 0) {
      lineItems = lineItems.replace(index, lineItem);
    } else {
      lineItems = lineItems.removeAt(index);
    }

    state = AsyncData(state.requireValue.copyWith(sale: sale.copyWith(items: lineItems)));
  }

  void removeLineItem({required int index}) {
    if (!state.hasValue) return;

    final sale = state.requireValue.sale;
    final lineItems = sale.items.removeAt(index);

    state = AsyncData(state.requireValue.copyWith(sale: sale.copyWith(items: lineItems)));
  }

  void clearDiscount({required int index}) {
    if (!state.hasValue) return;
    final sale = state.requireValue.sale;
    final items = sale.items;
    final cleared = items[index].copyWith(discount: null);

    var mergeIndex = -1;
    for (var i = 0; i < items.length; i++) {
      if (i == index) continue;
      if (items[i].discount == null && _isSameItem(items[i], cleared)) {
        mergeIndex = i;
        break;
      }
    }

    IList<LineItem> updatedItems;
    if (mergeIndex != -1) {
      final merged = items[mergeIndex].copyWith(
        quantity: items[mergeIndex].quantity + cleared.quantity,
      );
      updatedItems = items.removeAt(index);
      final adjustedMergeIndex = mergeIndex > index ? mergeIndex - 1 : mergeIndex;
      updatedItems = updatedItems.replace(adjustedMergeIndex, merged);
    } else {
      updatedItems = items.replace(index, cleared);
    }

    state = AsyncData(state.requireValue.copyWith(sale: sale.copyWith(items: updatedItems)));
  }

  void clearLineItems() {
    if (!state.hasValue) return;
    final sale = state.requireValue.sale;
    state = AsyncData(state.requireValue.copyWith(sale: sale.copyWith(items: const IList.empty())));
  }

  void addPayment(Payment payment) {
    if (!state.hasValue) return;
    final sale = state.requireValue.sale;
    state = AsyncData(state.requireValue.copyWith(sale: sale.copyWith(payment: payment)));
  }

  void clearPayment() {
    if (!state.hasValue) return;
    final sale = state.requireValue.sale;
    state = AsyncData(state.requireValue.copyWith(sale: sale.copyWith(payment: null)));
  }

  Future<void> confirmSale() async {
    if (!state.hasValue) return;

    state = const AsyncLoading();

    state = await AsyncValue.guard(() async {
      final OrderingData(:sale, :store, :cashier) = state.requireValue;
      final finalizeSale = ref.read(finalizeSaleProvider);

      final receipt = await finalizeSale(sale, store: store, cashier: cashier);

      return state.requireValue.copyWith(receipt: receipt);
    });
  }
}
