import 'dart:async';

import 'package:dart_mappable/dart_mappable.dart';
import 'package:fast_immutable_collections/fast_immutable_collections.dart';
import 'package:hooks_riverpod/hooks_riverpod.dart';

import '../../../utils/uuidv7.dart';
import '../entities/cashier.dart';
import '../entities/discount.dart';
import '../entities/line_item.dart';
import '../entities/payment.dart';
import '../entities/product.dart';
import '../entities/product_group.dart';
import '../entities/receipt.dart';
import '../entities/sale.dart';
import '../entities/store.dart';
import '../enums/sale_type.dart';
import '../repositories/cashier_repository.dart';
import '../repositories/product_group_repository.dart';
import '../repositories/product_repository.dart';
import '../repositories/store_repository.dart';
import '../use_cases/finalize_sale.dart';

part 'ordering_notifier.mapper.dart';

@MappableClass()
class OrderingData with OrderingDataMappable {
  const OrderingData({
    required this.store,
    required this.cashier,
    required this.sale,
    required this.productGroups,
    required this.products,
    this.selectedGroup,
    this.receipt,
  });

  final Store store;
  final Cashier cashier;
  final Sale sale;
  final IList<ProductGroup> productGroups;
  final IList<Product> products;
  final ProductGroup? selectedGroup;
  final Receipt? receipt;
}

final orderingProvider = AsyncNotifierProvider(OrderingNotifier.new, name: 'orderingProvider');

class OrderingNotifier extends AsyncNotifier<OrderingData> {
  @override
  Future<OrderingData> build() async {
    final storeRepository = ref.watch(storeRepositoryProvider);
    final cashierRepository = ref.watch(cashierRepositoryProvider);
    final productGroupRepository = ref.watch(productGroupRepositoryProvider);
    final productRepository = ref.watch(productRepositoryProvider);

    final (store, cashier, productGroups) =
        await (
          storeRepository.getCurrent(),
          cashierRepository.getCurrent(),
          productGroupRepository.getAll(),
        ).wait;

    if (productGroups.isEmpty) {
      return OrderingData(
        store: store,
        cashier: cashier,
        sale: Sale.autoGenerated(type: SaleType.dineIn),
        productGroups: productGroups,
        products: const IList.empty(),
      );
    }

    final products = await productRepository.getByGroup(productGroups.first);

    return OrderingData(
      store: store,
      cashier: cashier,
      sale: Sale.autoGenerated(type: SaleType.dineIn),
      productGroups: productGroups,
      selectedGroup: productGroups.first,
      products: products,
    );
  }

  void applyDiscount(
    Map<String, int> selectedQuantities,
    Discount? Function(LineItem lineItem, int quantity) buildDiscount,
  ) {
    if (!state.hasValue || selectedQuantities.isEmpty) return;

    final sale = state.requireValue.sale;
    final currentLineItems = sale.items;
    final newLineItems = <LineItem>[];

    for (final originalItem in currentLineItems) {
      final selectedQty = selectedQuantities[originalItem.id];

      if (selectedQty == null) {
        newLineItems.add(originalItem);
      } else {
        if (selectedQty >= originalItem.quantity) {
          final discount = buildDiscount(originalItem, selectedQty);
          newLineItems.add(originalItem.copyWith(discount: discount));
        } else {
          final remainingQty = originalItem.quantity - selectedQty;
          newLineItems.add(originalItem.copyWith(quantity: remainingQty, discount: null));

          final discountedItem = originalItem.copyWith(
            id: UuidV7.generate(),
            quantity: selectedQty,
          );
          final discount = buildDiscount(discountedItem, selectedQty);
          newLineItems.add(discountedItem.copyWith(discount: discount));
        }
      }
    }

    state = AsyncData(
      state.requireValue.copyWith(sale: sale.copyWith(items: newLineItems.toIList())),
    );
  }

  void selectSaleType(SaleType saleType) {
    if (!state.hasValue) return;
    final sale = state.requireValue.sale;
    state = AsyncData(state.requireValue.copyWith(sale: sale.copyWith(type: saleType)));
  }

  Future<void> selectGroup(ProductGroup group) async {
    if (!state.hasValue) return;

    state = AsyncData(state.requireValue.copyWith(selectedGroup: group));

    state = const AsyncLoading();

    state = await AsyncValue.guard(() async {
      final products = await ref.read(productRepositoryProvider).getByGroup(group);
      return state.requireValue.copyWith(products: products);
    });
  }

  void addLineItem(LineItem lineItem) {
    if (!state.hasValue) return;

    final sale = state.requireValue.sale;
    final lineItems = sale.items.add(lineItem);

    state = AsyncData(state.requireValue.copyWith(sale: sale.copyWith(items: lineItems)));
  }

  void replaceLineItem(LineItem lineItem, {required int index}) {
    if (!state.hasValue) return;

    final sale = state.requireValue.sale;
    var lineItems = sale.items;

    if (lineItem.quantity > 0) {
      lineItems = lineItems.replace(index, lineItem);
    } else {
      lineItems = lineItems.removeAt(index);
    }

    state = AsyncData(state.requireValue.copyWith(sale: sale.copyWith(items: lineItems)));
  }

  void removeLineItem({required int index}) {
    if (!state.hasValue) return;

    final sale = state.requireValue.sale;
    final lineItems = sale.items.removeAt(index);

    state = AsyncData(state.requireValue.copyWith(sale: sale.copyWith(items: lineItems)));
  }

  void clearLineItems() {
    if (!state.hasValue) return;
    final sale = state.requireValue.sale;
    state = AsyncData(state.requireValue.copyWith(sale: sale.copyWith(items: const IList.empty())));
  }

  void addPayment(Payment payment) {
    if (!state.hasValue) return;
    final sale = state.requireValue.sale;
    state = AsyncData(state.requireValue.copyWith(sale: sale.copyWith(payment: payment)));
  }

  Future<void> confirmSale() async {
    if (!state.hasValue) return;

    state = const AsyncLoading();

    state = await AsyncValue.guard(() async {
      final OrderingData(:sale, :store, :cashier) = state.requireValue;
      final finalizeSale = ref.read(finalizeSaleProvider);

      final receipt = await finalizeSale(sale, store: store, cashier: cashier);

      return state.requireValue.copyWith(receipt: receipt);
    });
  }
}
