import 'package:dart_mappable/dart_mappable.dart';
import 'package:decimal/decimal.dart';
import 'package:fast_immutable_collections/fast_immutable_collections.dart';

import '../../../utils/tax_calculator.dart';
import '../../../utils/uuidv7.dart';
import '../enums/sale_type.dart';
import 'line_item.dart';
import 'payment.dart';

part 'sale.mapper.dart';

@MappableClass()
class Sale with SaleMappable {
  const Sale({
    required this.id,
    required this.type,
    required this.items,
    required this.createdAt,
    this.payment,
    this.soNumber = '',
  });

  factory Sale.autoGenerated({required SaleType type}) => Sale(
    id: UuidV7.generate(),
    type: type,
    items: const IList.empty(),
    createdAt: DateTime.now(),
  );

  final String id;
  final SaleType type;
  final IList<LineItem> items;
  final DateTime createdAt;
  final Payment? payment;
  final String soNumber;

  Decimal get grossAmount => items.fold(Decimal.zero, (sum, item) => sum + item.grossAmount);

  Decimal get vatableAmount =>
      items
          .where((item) => !item.isVatExempt)
          .fold(Decimal.zero, (sum, item) => sum + item.totalAmount)
          .vatableAmount;

  Decimal get vatAmount =>
      items
          .where((item) => !item.isVatExempt)
          .fold(Decimal.zero, (sum, item) => sum + item.totalAmount)
          .vatAmount;

  Decimal get discountAmount => items.fold(Decimal.zero, (sum, item) => sum + item.discountAmount);

  Decimal get vatExemptSales =>
      items
          .where((item) => item.isVatExempt)
          .fold(Decimal.zero, (sum, item) => sum + item.grossAmount)
          .vatableAmount;

  Decimal get totalAmount => items.fold(Decimal.zero, (sum, item) => sum + item.totalAmount);
}
