import 'package:decimal/decimal.dart';
import 'package:fast_immutable_collections/fast_immutable_collections.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:pos_app/features/customer_display/entities/customer_display_snapshot.dart';
import 'package:pos_app/features/sales/entities/cashier.dart';
import 'package:pos_app/features/sales/entities/discount.dart';
import 'package:pos_app/features/sales/entities/line_item.dart';
import 'package:pos_app/features/sales/entities/payment.dart';
import 'package:pos_app/features/sales/entities/receipt.dart';
import 'package:pos_app/features/sales/entities/sale.dart';
import 'package:pos_app/features/sales/entities/selected_variant.dart';
import 'package:pos_app/features/sales/entities/store.dart';
import 'package:pos_app/features/sales/enums/sale_type.dart';

LineItem _lineItem({
  required int quantity,
  required Decimal price,
  String? variantName,
  Discount? discount,
}) {
  return LineItem(
    id: 'li-1',
    productId: 1,
    productName: 'Iced Coffee',
    categoryName: 'Drinks',
    productImage: '',
    quantity: quantity,
    variant: SelectedVariant(id: 1, name: variantName ?? 'Regular', price: price),
    modifiers: const IList.empty(),
    discount: discount,
  );
}

const _store = Store(
  legalName: 'Test Store',
  tin: '000',
  addressLine1: 'Addr 1',
  addressLine2: 'Addr 2',
  logo: 'https://example.com/logo.png',
);

void main() {
  group('CustomerDisplayLineItem.fromLineItem', () {
    test('maps quantity, product name, variant label, and gross line total', () {
      final item = _lineItem(quantity: 2, price: Decimal.parse('120.00'), variantName: 'Large');

      final result = CustomerDisplayLineItem.fromLineItem(item);

      expect(result.productName, 'Iced Coffee');
      expect(result.quantity, 2);
      expect(result.variantLabel, 'Large');
      expect(result.lineTotal, Decimal.parse('240.00'));
      expect(result.discountLabel, isNull);
      expect(result.discountAmount, Decimal.zero);
    });

    test('maps the discount label and amount when the item has a discount', () {
      final item = _lineItem(
        quantity: 1,
        price: Decimal.parse('120.00'),
        discount: const SeniorPwdDiscount(beneficiaryId: '1', beneficiaryName: 'Juan Dela Cruz'),
      );

      final result = CustomerDisplayLineItem.fromLineItem(item);

      expect(result.discountLabel, 'Senior Citizen / PWD');
      expect(result.discountAmount, item.discountAmount);
      expect(result.discountAmount, greaterThan(Decimal.zero));
    });
  });

  group('CustomerDisplayOrdering.fromSale', () {
    test('maps items and aggregate totals straight from Sale', () {
      final sale = Sale.autoGenerated(type: SaleType.dineIn).copyWith(
        items: IList([
          _lineItem(quantity: 2, price: Decimal.parse('120.00')),
          _lineItem(quantity: 1, price: Decimal.parse('180.00')),
        ]),
      );

      final result = CustomerDisplayOrdering.fromSale(sale);

      expect(result.items.length, 2);
      expect(result.subtotal, sale.grossAmount);
      expect(result.discount, sale.discountAmount);
      expect(result.tax, sale.vatAmount);
      expect(result.total, sale.totalAmount);
    });
  });

  group('CustomerDisplayIdle.fromStore', () {
    test('maps store name and logo', () {
      final result = CustomerDisplayIdle.fromStore(_store);

      expect(result.storeName, 'Test Store');
      expect(result.storeLogo, 'https://example.com/logo.png');
    });
  });

  group('CustomerDisplayThankYou.fromReceipt', () {
    test('maps the doc number', () {
      final receipt = Receipt(
        id: 'r-1',
        store: _store,
        cashier: Cashier.unknown(),
        docNumber: 'SO-001-2026-0001',
        docDate: DateTime(2026, 8, 14),
        type: SaleType.dineIn,
        payment: ZeroPayment(),
        items: const IList.empty(),
      );

      final result = CustomerDisplayThankYou.fromReceipt(receipt);

      expect(result.docNumber, 'SO-001-2026-0001');
    });
  });

  group('CustomerDisplaySnapshot map round-trip', () {
    test('CustomerDisplayIdle survives toMap/fromMap', () {
      const snapshot = CustomerDisplayIdle(storeName: 'Test Store', storeLogo: 'logo.png');

      final decoded = decodeCustomerDisplaySnapshot(snapshot.toTransportMap());

      expect(decoded, isA<CustomerDisplayIdle>());
      expect((decoded as CustomerDisplayIdle).storeName, 'Test Store');
      expect(decoded.storeLogo, 'logo.png');
    });

    test('CustomerDisplayOrdering survives toMap/fromMap', () {
      final snapshot = CustomerDisplayOrdering(
        items: [
          CustomerDisplayLineItem(
            productName: 'Iced Coffee',
            quantity: 2,
            variantLabel: 'Large',
            lineTotal: Decimal.zero,
            discountAmount: Decimal.zero,
          ),
        ],
        subtotal: Decimal.parse('240.00'),
        discount: Decimal.zero,
        tax: Decimal.zero,
        total: Decimal.parse('240.00'),
      );

      final decoded = decodeCustomerDisplaySnapshot(snapshot.toTransportMap());

      expect(decoded, isA<CustomerDisplayOrdering>());
      expect((decoded as CustomerDisplayOrdering).items.single.productName, 'Iced Coffee');
      expect(decoded.total, Decimal.parse('240.00'));
    });

    test('CustomerDisplayThankYou survives toMap/fromMap', () {
      const snapshot = CustomerDisplayThankYou(docNumber: 'SO-001-2026-0001');

      final decoded = decodeCustomerDisplaySnapshot(snapshot.toTransportMap());

      expect(decoded, isA<CustomerDisplayThankYou>());
      expect((decoded as CustomerDisplayThankYou).docNumber, 'SO-001-2026-0001');
    });

    test(
      'decodes a real platform-channel-shaped payload (nested Map<Object?, Object?>/List<Object?>)',
      () {
        // Regression test for a real production bug: toTransportMap()/decode
        // round-tripped fine in-process (the tests above), but
        // desktop_multi_window's IPC round-trips arguments through Flutter's
        // StandardMethodCodec, which decodes *nested* maps/lists as
        // Map<Object?, Object?>/List<Object?> — not Map<String, dynamic> —
        // regardless of what was sent. dart_mappable's decoder rejects that
        // shape. This constructs the payload the way the real channel
        // actually delivers it, instead of the same-isolate shortcut above.
        final Map<Object?, Object?> channelShaped = {
          'type': 'ordering',
          'items': <Object?>[
            <Object?, Object?>{
              'productName': 'Iced Coffee',
              'quantity': 2,
              'variantLabel': 'Large',
              'lineTotal': '240.00',
              'discountAmount': '0',
            },
          ],
          'subtotal': '240.00',
          'discount': '0',
          'tax': '0',
          'total': '240.00',
        };

        final decoded = decodeCustomerDisplaySnapshot(channelShaped);

        expect(decoded, isA<CustomerDisplayOrdering>());
        expect((decoded as CustomerDisplayOrdering).items.single.productName, 'Iced Coffee');
        expect(decoded.total, Decimal.parse('240.00'));
      },
    );
  });
}
